# Generated by Django 3.0.7 on 2020-06-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0002_auto_20200613_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='gatetime',
            new_name='datetime',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
