# Generated by Django 3.0.7 on 2020-06-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0004_auto_20200613_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='datetime',
            field=models.DateField(),
        ),
    ]
